### ISSUE TITLE
Fix AppVeyor tests

### ISSUE THREAD

**Issue by vweevers** [vweevers/remark-git-contributors#14]
```
Error: Command failed: git commit -m initial --author test <test@localhost>
    at checkExecSyncError (child_process.js:473:13)
    at execFileSync (child_process.js:493:13)
    at run (C:\projects\remark-git-contributors\test\index.js:42:3)
    at Test.<anonymous> (C:\projects\remark-git-contributors\test\index.js:16:3)
```

**Comment by vweevers** [comment]
With stdio inherited:

```
TAP version 13
# basic
Initialized empty Git repository in C:/Users/appveyor/AppData/Local/Temp/1/remark-git-contributors/1529835346775/.git/
*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address (got 'appveyor@APPVYR-WIN.(none)')
child_process.js:496
    throw err;
    ^
Error: Command failed: git commit -m initial --author test <test@localhost>
```

**Comment by vweevers** [comment]
Is it a quoting issue? The `--author` flag works locally 🤔
